version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: laminas/laminas-feed
    versions:
    - 2.13.1
    - 2.14.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.81
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
